export const TEAM_MEMBERS = [
  {
    image: "/img/team/universa-team-alex.jpg",
    name: "Alex Vedanta",
    role: "",
    quote: "A simple thought is the fundament of any material manifestation",
    linkedIn: "",
  },
  {
    image: "/img/team/universa-team-michal.jpeg",
    name: "Michal Wro",
    role: "Enterprise Project Vanguard",
    quote: "Intellectualism is a common cover-up for fear of direct experience",
    linkedIn: "https://www.linkedin.com/in/michalwro/",
  },
  {
    image: "/img/team/universa-team-kama.jpeg",
    name: "Kama Woy",
    role: "Head of Growth",
    quote:
      "Deep in the human unconscious is a pervasive need for a logical universe that makes sense. But the real universe is always one step beyond logic.",
    linkedIn: "https://www.linkedin.com/in/kama-woynarska/",
  },
  {
    image: "/img/team/universa-team-maxim.jpeg",
    name: "Maxim",
    role: "Developer",
    quote: "TBA",
    // linkedIn: "https://www.linkedin.com/in/maxim-kasakin/",
  },
  {
    image: "/img/team/universa-team-wiola.jpeg",
    name: "Wioleta Hutniczak",
    role: "Grants Jedi & Digital Marketing",
    quote: 'For this particular moment of my life: "Music is the answer"',
    linkedIn: "https://www.linkedin.com/in/wioleta-hutniczak-37719011a/",
  },
  {
    image: "/img/team/universa-team-shirsho.jpeg",
    name: "Shirsho",
    role: "Software Engineer",
    quote: "When times are good, be grateful. When it's tough, be graceful.",
    // linkedIn: "https://www.linkedin.com/in/shirsho-dipto/",
  },
  {
    image: "/img/team/universa-team-kamil.jpeg",
    name: "Kamil",
    role: "AI Team Lead",
    quote: "Blame it on the boogie",
    // linkedIn: "https://www.linkedin.com/in/kamilklecha/",
  },
  {
    image: "/img/team/universa-team-cosmin.jpeg",
    name: "Cosmin Lungu",
    role: "Podcast Host",
    quote: "Alone we can do so little, together we can do so much",
    linkedIn: "https://www.linkedin.com/in/cosminlungu/",
  },
  {
    image: "/img/team/universa-team-maira.jpeg",
    name: "Maira Murillo",
    role: "Project Manager",
    quote: "It’s ok to change your mind. Stay true to yourself",
    linkedIn: "https://www.linkedin.com/in/mairamurilloa/",
  },
  {
    image: "/img/team/universa-team-nics.jpeg",
    name: "Nics Pawlee",
    role: "Marketing Coordinator",
    quote: "Be Gentle with yourself and others ",
    linkedIn: "https://www.linkedin.com/in/nics-p",
  },
  {
    image: "/img/team/universa-team-miko.jpeg",
    name: "Mikołaj Antonik",
    role: "Product Designer",
    quote: "Less is more",
    linkedIn: "https://www.linkedin.com/in/mikolajantonik/",
  },
  {
    image: "/img/team/universa-team-vince.jpeg",
    name: "Vince",
    role: "Discord and Twitter Manager",
    quote: "Be yourself and be 1% better everyday",
    linkedIn: "",
  },
  {
    image: "/img/team/universa-team-bart.jpeg",
    name: "Bart Spasowski",
    role: "Video creator / editor",
    quote: "Less is more",
    linkedIn: "https://linkedin.com/in/spaso",
  },
];
