const API_URL = process.env.NEXT_PUBLIC_API_URL;
const OPENAI_API_KEY = process.env.NEXT_PUBLIC_OPENAI_API_KEY;
const SIMLI_API_KEY = process.env.NEXT_PUBLIC_SIMLI_API_KEY;
const ELEVEN_API_KEY = process.env.NEXT_PUBLIC_XI_API_KEY;
const AGENT_ID = process.env.NEXT_PUBLIC_PUBLIC_AGENT_ID;


export { API_URL, OPENAI_API_KEY, SIMLI_API_KEY, ELEVEN_API_KEY, AGENT_ID };
